name: CI

on:
  push:
    branches: [ "dev", "stable", "main" ]
  pull_request:
    branches: [ "dev", "stable", "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      # Check out the repo
      - name: Check out the repo
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Lint Python code
      - name: Lint Python code with Flake8
        run: |
          pip install flake8
          flake8 .

      # Run Python unittests
      - name: Run Python unittests
        run: |
          python -m unittest discover -s tests -v

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      # Trivy scan image built by the build step
      - name: Trivy scan image
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'myapp:latest'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

      # Trivy scan filesystem of the repo
      - name: Trivy scan filesystem
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          path: '.'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
